package StoreApp;


/**
* StoreApp/DSMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from storeApp.idl
* Friday, October 23, 2020 4:50:23 o'clock PM EDT
*/

public interface DSMS extends DSMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DSMS
