package StoreApp;

/**
* StoreApp/DSMSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from storeApp.idl
* Friday, October 23, 2020 10:47:07 o'clock AM EDT
*/

public final class DSMSHolder implements org.omg.CORBA.portable.Streamable
{
  public StoreApp.DSMS value = null;

  public DSMSHolder ()
  {
  }

  public DSMSHolder (StoreApp.DSMS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StoreApp.DSMSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StoreApp.DSMSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StoreApp.DSMSHelper.type ();
  }

}
